stages:
  - build_and_push
  - deploy

variables:
  IMAGE_NAME: $DOCKERHUB_USERNAME/mynginx

build_and_push:
  stage: build_and_push
  image: docker:latest
  services:
    - docker:dind
  script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        IMAGE_TAG="$CI_COMMIT_TAG"
      else
        IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
      fi

      echo "Using tag: $IMAGE_TAG"

      docker build --no-cache -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      docker push $IMAGE_NAME:$IMAGE_TAG
      docker push $IMAGE_NAME:latest
  only:
    - main
    - tags

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - export KUBECONFIG=$KUBECONFIG
    - kubectl set image deployment/dp-nginx nginx=$IMAGE_NAME:latest --namespace=app
  only:
    - main
    - tags