stages:
  - build
  - push

variables:
  IMAGE_NAME: $DOCKERHUB_USERNAME/your-image-name

# Определим тег для образа:
# если это git-тег — используем его, иначе используем короткий SHA коммита
before_script:
  - |
    if [[ -n "$CI_COMMIT_TAG" ]]; then
      export IMAGE_TAG="$CI_COMMIT_TAG"
    else
      export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
    fi

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - main